### PR TITLE
RegisterFiles Within Address Blocks (and Nested)

### PR DESCRIPTION
**Pull request by DanChianucci**
So this is a pretty huge merge request,

I've added preliminary support for editing nested register files to the memoryMaps editor:

1.    Register Files now are displayed in the left hand tree view, as well as the right hand memory layout view.
2.   There is a new model, delegate,editor and SingleEditor for registerMaps.
3.   The table view class that shows the registers is shared between the addressBlock and registerFile editors.
    -  It now allows you to add a registerFile or register in the right click menu
    -  It also differentiates between the two using a hierarchy icon next to the registerFiles
    -  Fields which are present in one type and no in the other are greyed out and disabled

### CODE REVIEW

**Comment by DanChianucci** [comment]
Some deficiencies I know about currently are:

1.  The RegisterFileValidator doesn't actually validate the registerData yet.  If a register inside a registerFile is invalid it still shows up red, but the red doesn't propagate up the tree.  In turn there is no warning about errors when you try to save. Registers directly inside an address block still work as expected.

2.  it looks like when an item is added, onAddItem calls getAllRegisterOffsets, and then computes a new offset based on the maximum.  I couldn't quite figure out what this was doing, but I'm pretty sure that since the container can now hold registerFiles, it needs to take into account the registerFile ranges and dimensions

3. I believe Copying and pasting registerFiles doesn't correctly update the reference count for expressions.  If I manually update the reference count from the parameters editor It looks to correct the situation.

**Comment by DanChianucci** [comment]
Also the AddressBlock and registerFile models are hare a lot of common code.  It would probably be beneficial to move it to a common subclass or something.

**Comment by epekkar** [comment]
Thank you, Dan! 
RegisterFiles are a nice add to the component memory definitions. We'll look into merging this once we get some of the ongoing work out of the way.

**Comment by DanChianucci** [comment]
This should also reduce the need for dynamic casts to see whether an object is a register or a registerFile.

**Pull request merged**
