### PR TITLE
.qmake.conf: fix libpath and INSTALL_ROOT

### PR DESCRIPTION
**Pull request by vowstar**
## ``lib_path`` bitness problem

Lib path depend on the bitness of the system, ``lib_path = /usr/lib`` should
on 32 bit system and lib_path = /usr/lib64 should on 64 bit system.

## ``unix:config.extra`` problem

The string in ``unix:config.extra`` caused hidden bugs when install.
After ``.qmake.conf`` automatic expanded into Makefile, it will get:
```Makefile
install_config: FORCE
	@test -d $(INSTALL_ROOT)/etc/xdg/TUT || mkdir -p $(INSTALL_ROOT)/etc/xdg/TUT
	cp ./Administrative/releaseFiles/DefaultSettingsLinux.ini /etc/xdg/TUT/Kactus2.ini; (test -d /usr/lib64 && ln -f -s /usr/bin/kactus2 /usr/lib64/libKactus2.so) || (test -d /lib/x86_64-linux-gnu && ln -f -s /usr/bin/kactus2 /lib/x86_64-linux-gnu/libKactus2.so)
```
It have 2 problems:
- ``$(INSTALL_ROOT)`` works everywhere but not in ``unix:
  config.extra``, this will make it difficult to use this variable in QT
  when running ``make -j1 INSTALL_ROOT="${D}" install``, and
  ``$(INSTALL_ROOT)/etc/xdg/TUT`` may not equal as ``/etc/xdg/TUT``
- ``/etc/xdg/TUT`` may not created when running ``cp
  ./Administrative/releaseFiles/DefaultSettingsLinux.ini
  /etc/xdg/TUT/Kactus2.ini;`` when compile in parallel, so ``make -j install`` is prone to problems

So some workarounds shoud add into ``unix:config.extra``

### CODE REVIEW

**Comment by epekkar** [comment]
Hi vowstar,

I ended up cleaning the overall install process and re-arranged some files/instructions. Please let me know, if the changed qmake configuration now works for your intended purpose.

**Comment by vowstar** [comment]
@epekkar Thank you!

I'm using latest code https://github.com/kactus2/kactus2dev/pull/37/commits/dcf51b90535e5a73a03f266a8a7f8c31a5c674ac in a clean linux environment to compile, but got ``cannot find -lKactus2`` error, I'm looking for how to fix that

```
g++ -Wl,-O1 -shared -o libMCAPICodeGenerator.so release/NameGenerationPolicy.o release/CSourceWriter.o release/MCAPICodeGenerator.o release/MCAPICodeGeneratorPlugin.o release/MCAPIHeaderGenerator.o release/MCAPIParser.o release/qrc_MCAPICodeGenerator.o release/moc_MCAPICodeGeneratorPlugin.o  -L./../../executable -lIPXACTmodels -lKactus2 /usr/lib64/libQt5Widgets.so /usr/lib64/libQt5Gui.so /usr/lib64/libQt5Xml.so /usr/lib64/libQt5Core.so -lGL -lpthread
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lKactus2
collect2: error: ld returned 1 exit status
```

**Comment by vowstar** [comment]
Hi @epekkar, 

I found the cause of the above bug.
The MCAPICodeGenerator and VHDLGenerator linked with "-lKactus2", so Kactus2 should add as dependencies of them to fix build error.

After this modification, such a build error will no longer occur in parallel compilation.

It works!

**Comment by epekkar** [comment]
Thank you, vowstar.
I must have dropped the dependencies by accident at some point during testing between Windows and Linux environments. The install process should run smoother now.

**Pull request merged**
